name: Automation Web and API Workflow

on:
  workflow_dispatch:
    inputs: { }
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  run-api-automation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup gradlew
        run: chmod +x gradlew

      - name: Execute API Test
        run: ./gradlew -Ptags="@api"

      - name: Archive Test Result
        uses: actions/upload-artifact@v4.3.0
        if: always()
        with:
          name: Cucumber Report API
          path: reports

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          PERSONAL_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          PUBLISH_DIR: reports

  run-web-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Wait
        uses: NathanFirmo/wait-for-other-job@v1.1.1
        with:
          token: ${{ secrets.TOKEN_DEPLOY_FINAL_PROJECT }}
          job: 'run-api-automation'
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v0.0.0

      - name: Setup gradlew
        run: chmod +x gradlew

      - name: Execute Web Test
        run: ./gradlew -Ptags="@web"

      - name: Archive Test Result
        uses: actions/upload-artifact@v4.3.0
        if: always()
        with:
          name: Cucumber Report WEB
          path: reports
          
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          PERSONAL_TOKEN: ${{ secrets.TOKEN_DEPLOY_FINAL_PROJECT }}
          PUBLISH_DIR: reports
